package me.mitul.aij.model

data class Collage(
    val id: Int,
    val name: String,
    val collageFees: Int,
    val branches: String,
    val hostel: String,
    val code: String,
    val clgCollageId: Int,
    val initials: String,
    val fullName: String,
    val address: String,
    val phone: String,
    val web: String,
    val email: String,
    val fees: String,
    val type: String,
    val university: String,
    val vecStr: String,
    val warningMessage: String,
    val branch: String,
    val seat: Int,
    val vacant: Int,
)
