package me.mitul.aij.model

data class Collage(
    var id: Int = 0,
    var name: String = "",
    var collageFees: Int = 0,
    var branches: String = "",
    var hostel: String = "",
    var code: String = "",
    var clgCollageId: Int = 0,
    var initials: String = "",
    var fullName: String = "",
    var address: String = "",
    var phone: String = "",
    var web: String = "",
    var email: String = "",
    var fees: String = "",
    var type: String = "",
    var university: String = "",
    var vecStr: String = "",
    var warningMessage: String = "",
    var branch: String = "",
    var seat: Int = 0,
    var vacant: Int = 0,
)
